#pragma once

// Generated by calibrate_train_update.py
// Window samples: 200
// Step samples: 50
// Raw normalization: rest = none median, calib = overall 95th percentile
// Feature order: MAV_ch1_norm, MAV_ch2_norm, RMS_ch1_norm, RMS_ch2_norm, WL_ch1_norm, WL_ch2_norm, MAV_diff, RMS_diff, WL_diff, MAV_sum, RMS_sum, WL_sum, MAV_balance, RMS_balance, WL_balance

int predictEMG(float *x) {
    if (x[11] <= 0.179981017f) {
        return 2;
    } else {
        if (x[12] <= -0.01621893141f) {
            return 1;
        } else {
            if (x[8] <= -0.04715042002f) {
                if (x[3] <= 0.7052450478f) {
                    return 1;
                } else {
                    return 0;
                }
            } else {
                return 0;
            }
        }
    }
}
