#pragma once

// Generated by calibrate_train_update.py
// Window samples: 200
// Step samples: 50
// Feature order: MAV_ch1, MAV_ch2, RMS_ch1, RMS_ch2, WL_ch1, WL_ch2, MAV_diff, RMS_diff, WL_diff, MAV_sum, RMS_sum, WL_sum, MAV_balance, RMS_balance, WL_balance

int predictEMG(float *x) {
    if (x[11] <= 21837.5f) {
        return 2;
    } else {
        if (x[9] <= 733.2149963f) {
            return 1;
        } else {
            return 0;
        }
    }
}
