#pragma once

// Generated by calibrate_train_update.py
// Window samples: 200
// Step samples: 100
// Feature order: MAV_ch1, MAV_ch2, RMS_ch1, RMS_ch2, WL_ch1, WL_ch2, MAV_diff, RMS_diff, WL_diff, MAV_sum, RMS_sum, WL_sum, MAV_balance, RMS_balance, WL_balance

int predictEMG(float *x) {
    if (x[11] <= 2081.5f) {
        return 2;
    } else {
        if (x[12] <= 0.006119620055f) {
            if (x[4] <= 19607.5f) {
                if (x[6] <= -0.6599999964f) {
                    if (x[11] <= 8782.0f) {
                        return 0;
                    } else {
                        return 4;
                    }
                } else {
                    if (x[2] <= 67.77761078f) {
                        return 4;
                    } else {
                        return 0;
                    }
                }
            } else {
                if (x[12] <= -0.01477864059f) {
                    if (x[1] <= 123.8025017f) {
                        return 4;
                    } else {
                        return 0;
                    }
                } else {
                    return 0;
                }
            }
        } else {
            if (x[6] <= 7.277499914f) {
                if (x[2] <= 80.17727661f) {
                    if (x[1] <= 32.24500084f) {
                        return 1;
                    } else {
                        return 1;
                    }
                } else {
                    if (x[12] <= 0.01409404585f) {
                        return 3;
                    } else {
                        return 3;
                    }
                }
            } else {
                return 1;
            }
        }
    }
}
